site_name: risoria's blog
site_url: https://ret2home.github.io/blog/
repo_url: https://github.com/ret2home/blog/
repo_name: ret2home/blog
site_author: "ret2home"
site_description: >-
  @ret2home のブログや CTF の Writeup など
theme:
  name: material
  custom_dir: overrides
  language: ja
  favicon: assets/avatar.png
  features:
    - navigation.tabs
  icon:
    logo: material/console
  palette:
    primary: deep purple

extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ret2home/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ret2home

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: "ret2home"
      repo: blog
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
  - search
  - git-revision-date-localized

nav:
  - Home: index.md
  - 競プロ:
    - JOI 2021/2022 本選参加記: kyopro/joi2022-ho/index.md
    - JOI 2020/2021 本選参加記: kyopro/joi2021-ho/index.md
    - JOI 2020/2021 二次予選参加記: kyopro/joi2021-yo/index.md
    - JOI 2019/2020 春合宿参加記: kyopro/joi2020-sp/index.md
    - JOI 2019/2020 本選参加記: kyopro/joi2020-ho/index.md
  - CTF:
    - Metared CTF 5th Stage writeup: CTF/metared2021-5/index.md
    - picoCTF 2021 writeup:
      - overview: CTF/picoctf-2021/index.md
      - pwn:
        - Binary Gauntlet: CTF/picoctf-2021/pwn/gauntlet/index.md
        - Cache Me Outside:  CTF/picoctf-2021/pwn/cacheme/index.md
        - Here's a LIBC: CTF/picoctf-2021/pwn/hereslibc/index.md
        - Unsubscriptions Are Free: CTF/picoctf-2021/pwn/unsubsc/index.md
        - filtered-shellcode: CTF/picoctf-2021/pwn/filtered/index.md
        - Kit Engine: CTF/picoctf-2021/pwn/kitengine/index.md
        - Download Horsepower: CTF/picoctf-2021/pwn/horsepower/index.md
      - rev:
        - gogo: CTF/picoctf-2021/rev/gogo/index.md
        - Easy as GDB: CTF/picoctf-2021/rev/easyasgdb/index.md
        - powershelly: CTF/picoctf-2021/rev/powershelly/index.md
        - Rolling My Own: CTF/picoctf-2021/rev/rolling/index.md
        - checkpass: CTF/picoctf-2021/rev/checkpass/index.md
    - 防衛省 CTF 参加記 : CTF/modctf-2021/index.md
    - zer0pts CTF 2021 writeup: CTF/zer0pts-ctf-2021/index.md
    - 0x41414141 CTF Writeup (pwn only): CTF/0x41414141-pwn/index.md
    - Paken CTF 2020 運営記: CTF/pakenctf2020/index.md
  - 旅行記他:
    - UFOキャッチャー制作中間記録・七模擬まで: others/nanamogi/index.md
    - Thailand International Science Fair 2023 参加記: others/TISF2023/index.md
    - 関西旅行記2 〜マスフェスタ参加記を添えて〜: others/kansai-trip2/index.md
    - 灘校文化祭訪問記: others/ndfes2022/index.md
    - パ研合宿 2021 運営記: others/pakencamp2021/index.md